/**
 * LabReview — direction-specific practical guidance.
 *
 * Each marker has a separate HIGH and LOW pathway. These are educational,
 * cause-dependent summaries, not instructions to self-treat. The evidence links
 * remain attached to the marker's main guidance object in data.js.
 */
(function (B) {
  'use strict';

  const d = (aim, lifestyle, clinical) => ({ aim, lifestyle, clinical });
  const advice = {
    ldl: {
      high: d('Goal: lower LDL-C and overall atherogenic-particle exposure when cardiovascular risk warrants it.',
        ['Lowers LDL-C: replace saturated fats with unsaturated fats.', 'Lowers LDL-C modestly: add soluble fibre; regular activity and weight loss can help when relevant.'],
        ['Lowers LDL-C: statins are usually first-line; ezetimibe, bempedoic acid or PCSK9-targeting therapy may be added according to risk and response.']),
      low: d('Goal: do not deliberately raise an otherwise unexplained low LDL-C; confirm the value and look for a cause when clinically relevant.',
        ['Usually no food or supplement is needed to raise LDL-C.', 'Addresses a cause rather than the number: review inadequate intake, weight loss or symptoms of thyroid/serious illness.'],
        ['Raises LDL-C only indirectly: treatment is directed at an identified cause such as hyperthyroidism, malabsorption or undernutrition.']),
    },
    hdl: {
      high: d('Goal: do not try to lower HDL-C solely because it is high; very high values are interpreted with the complete lipid pattern.',
        ['No lifestyle intervention is recommended just to lower HDL-C.', 'Reduces overall risk without targeting HDL-C: avoid tobacco, remain active and control blood pressure.'],
        ['No medicine is prescribed solely to lower high HDL-C; clinicians treat the underlying lipid disorder and overall risk.']),
      low: d('Goal: improve cardiovascular risk rather than chasing a higher HDL-C number.',
        ['May raise HDL-C modestly and improves risk: stop smoking, exercise regularly and reduce excess weight when relevant.', 'Improves the lipid pattern: replace refined carbohydrates and saturated fat with fibre-rich foods and unsaturated fats.'],
        ['Medicines are not used solely to raise HDL-C; LDL-C, non-HDL-C, ApoB and triglycerides are treated according to risk.']),
    },
    triglycerides: {
      high: d('Goal: lower triglycerides; very high levels also require pancreatitis-risk reduction.',
        ['Lowers triglycerides: reduce or avoid alcohol, sugary drinks and refined carbohydrates.', 'Lowers triglycerides: regular activity and sustainable weight loss when relevant.'],
        ['Lowers cardiovascular risk: statin therapy when indicated.', 'Lowers severe triglycerides: fibrate or prescription omega-3 therapy may be used after clinical assessment.']),
      low: d('Goal: do not raise a low triglyceride result unless an underlying nutrition, thyroid or absorption problem is identified.',
        ['Addresses a possible cause: ensure adequate energy and fat intake if intake is genuinely low.', 'Do not add sugar or alcohol to raise triglycerides.'],
        ['Raises the value only indirectly: treat an identified cause such as hyperthyroidism, malabsorption or undernutrition.']),
    },
    'total-cholesterol': {
      high: d('Goal: lower the atherogenic components—not total cholesterol in isolation.',
        ['Lowers LDL/non-HDL components: replace saturated fat with unsaturated fat and add soluble fibre.', 'Lowers triglyceride-related components: reduce refined carbohydrates and alcohol when elevated.'],
        ['Lowers atherogenic cholesterol: risk-based statin therapy and selected add-on treatment.']),
      low: d('Goal: do not deliberately raise total cholesterol; confirm and evaluate an unexpectedly low result in context.',
        ['Addresses a possible cause: review inadequate intake, unintentional weight loss or malabsorption symptoms.', 'Do not add saturated fat simply to raise the number.'],
        ['Raises the result only indirectly: treat an identified cause such as hyperthyroidism, malnutrition or severe illness.']),
    },
    'non-hdl': {
      high: d('Goal: lower cholesterol carried by atherogenic particles.',
        ['Lowers non-HDL-C: replace saturated fat with unsaturated fat, increase soluble fibre and reduce refined carbohydrates.', 'Lowers it when metabolic risk contributes: exercise and sustainable weight loss.'],
        ['Lowers non-HDL-C: statins are commonly first-line; selected add-on therapy depends on risk and response.']),
      low: d('Goal: do not deliberately raise a low non-HDL-C result.',
        ['No dietary change is needed just to raise non-HDL-C.', 'Review inadequate intake, weight loss or thyroid symptoms if the result is unexpected.'],
        ['Treatment is directed at an identified cause rather than raising non-HDL-C.']),
    },
    apob: {
      high: d('Goal: lower the number of circulating atherogenic particles.',
        ['Lowers ApoB-containing particles: use an LDL-lowering pattern with less saturated fat and more soluble fibre.', 'Lowers ApoB when insulin resistance contributes: activity, weight management and glucose control.'],
        ['Lowers ApoB: statins; ezetimibe, bempedoic acid or PCSK9-targeting therapy may add lowering for selected people.']),
      low: d('Goal: do not deliberately raise ApoB; investigate only when an unexpectedly low value fits symptoms or illness.',
        ['No lifestyle intervention is needed to raise ApoB.', 'Address inadequate intake or malabsorption only if confirmed.'],
        ['Treatment targets an identified thyroid, liver, nutrition or inherited condition—not the ApoB number itself.']),
    },
    lpa: {
      high: d('Goal: reduce total cardiovascular risk; lifestyle usually does not materially lower genetically determined Lp(a).',
        ['Does not reliably lower Lp(a), but lowers overall risk: exercise, avoid tobacco, control blood pressure and eat a heart-healthy diet.'],
        ['Lowers LDL-related risk: clinicians may intensify LDL-lowering therapy.', 'Modestly lowers Lp(a): PCSK9-targeting therapy; apheresis is reserved for selected very-high-risk cases.']),
      low: d('Goal: no increase is needed; low Lp(a) is generally favorable.',
        ['No lifestyle action is needed to raise Lp(a).'],
        ['No treatment is used to raise Lp(a).']),
    },
    hscrp: {
      high: d('Goal: lower the underlying inflammation or cardiovascular risk—not hs-CRP as an isolated target.',
        ['May lower persistent hs-CRP and improves health: stop smoking, exercise, improve sleep and reduce excess weight when relevant.', 'Avoid hard exercise before a confirmation sample and repeat when well.'],
        ['Lowers hs-CRP by treating the cause: diagnosis-specific infection or inflammatory-disease treatment.', 'Statins may lower hs-CRP but are selected from cardiovascular risk, not this number alone.']),
      low: d('Goal: no increase is needed; low hs-CRP is not a deficiency.',
        ['No lifestyle action is needed to raise hs-CRP.'],
        ['No medicine is used to raise hs-CRP.']),
    },
    hba1c: {
      high: d('Goal: lower average glucose and reduce diabetes-related risk.',
        ['Lowers HbA1c: regular aerobic and resistance activity.', 'Lowers HbA1c when appropriate: sustainable 5–7% weight loss and a fibre-rich eating pattern with fewer sugary drinks/refined carbohydrates.'],
        ['Lowers HbA1c: treatment is individualized and may include metformin, GLP-1-based therapy, SGLT2 inhibitors, insulin or other medicines.']),
      low: d('Goal: prevent hypoglycaemia and identify falsely low HbA1c rather than trying to raise the laboratory number.',
        ['Raises low glucose safely when relevant: use consistent meals and avoid alcohol without food.', 'Does not correct a false reading: blood loss or shortened red-cell survival requires evaluation.'],
        ['Raises HbA1c only indirectly: review excessive glucose-lowering treatment and treat the cause of altered red-cell survival.']),
    },
    glucose: {
      high: d('Goal: lower glucose and confirm whether the elevation is persistent.',
        ['Lowers glucose: activity, fibre-rich meals, fewer sugary drinks/refined carbohydrates and sustainable weight loss when appropriate.', 'Improves repeat accuracy: standardize fasting conditions.'],
        ['Lowers glucose: medication is individualized and may include metformin, GLP-1-based therapy, SGLT2 inhibitors, insulin or other agents.']),
      low: d('Goal: raise glucose promptly when true hypoglycaemia is present and prevent recurrence.',
        ['Raises glucose during mild confirmed hypoglycaemia: follow an established fast-acting-carbohydrate plan.', 'Prevents recurrence: regular meals and avoiding alcohol without food.'],
        ['Raises glucose and prevents recurrence: review insulin or other glucose-lowering therapy with a prescriber; severe symptoms require urgent treatment.']),
    },
    alt: {
      high: d('Goal: lower ALT by removing or treating the source of liver or muscle injury.',
        ['May lower ALT when relevant: reduce or avoid alcohol, improve metabolic health and avoid hard exercise before a repeat.', 'Prevents avoidable injury: review supplements with a clinician or pharmacist.'],
        ['Lowers ALT by treating the cause: diagnosis-specific metabolic, viral, autoimmune or medication-related management.']),
      low: d('Goal: usually no increase is needed; very low ALT is interpreted with muscle mass, nutrition and frailty.',
        ['May raise a very low value only indirectly: adequate nutrition and resistance activity can support muscle when appropriate.'],
        ['Treatment targets confirmed undernutrition, vitamin deficiency or frailty—not ALT itself.']),
    },
    ast: {
      high: d('Goal: lower AST by identifying whether the source is liver, muscle or another tissue.',
        ['May lower AST when relevant: avoid alcohol and hard exercise before repeat testing.', 'Review medicines and supplements rather than stopping them independently.'],
        ['Lowers AST by treating the identified liver or muscle cause; CK and liver-panel testing may guide the pathway.']),
      low: d('Goal: usually no increase is needed; low AST can accompany low muscle mass or vitamin B6 deficiency.',
        ['May raise a very low result indirectly: adequate nutrition and resistance exercise when appropriate.'],
        ['Treat a confirmed nutrition, muscle or frailty-related cause—not AST itself.']),
    },
    alp: {
      high: d('Goal: lower ALP by identifying and treating its liver/bile-duct or bone source.',
        ['No universal lifestyle method directly lowers ALP.', 'May lower it indirectly: correct a confirmed vitamin D or nutrition problem, or address alcohol/metabolic risk if liver disease is involved.'],
        ['Lowers ALP by treating the cause: relieve obstruction, treat cholestatic liver disease or manage the responsible bone/endocrine disorder.']),
      low: d('Goal: raise ALP only by treating a confirmed nutrition, thyroid or rare bone-enzyme disorder.',
        ['May raise low ALP indirectly: correct confirmed zinc/magnesium deficiency and inadequate nutrition.'],
        ['Treat hypothyroidism or hypophosphatasia when diagnosed; ALP itself is not treated.']),
    },
    ggt: {
      high: d('Goal: lower GGT by addressing alcohol exposure, metabolic liver risk, cholestasis or a contributing medicine.',
        ['May lower GGT: reduce or avoid alcohol and improve metabolic health through activity and weight management when relevant.', 'Review medicines and supplements rather than stopping them independently.'],
        ['Lowers GGT by treating the cause; GGT itself has no specific drug treatment.']),
      low: d('Goal: no increase is needed; low GGT is generally not clinically important.',
        ['No lifestyle action is needed to raise GGT.'],
        ['No treatment is used to raise GGT.']),
    },
    bilirubin: {
      high: d('Goal: lower bilirubin by distinguishing unconjugated from conjugated causes and treating the pathway.',
        ['May reduce benign Gilbert-related fluctuation: regular meals and normal hydration.', 'Does not replace evaluation: new jaundice should not be managed with lifestyle alone.'],
        ['Lowers bilirubin by treating the cause, such as haemolysis/hepatitis or bile-duct obstruction; Gilbert syndrome needs no drug treatment.']),
      low: d('Goal: no increase is needed; low bilirubin is common and not a deficiency.',
        ['No lifestyle action is needed to raise bilirubin.'],
        ['No treatment is used to raise bilirubin.']),
    },
    albumin: {
      high: d('Goal: correct the concentration only if dehydration or another cause is confirmed.',
        ['May lower a dehydration-related concentration: return to normal hydration when medically safe; do not force fluids.'],
        ['Lowers albumin indirectly by treating dehydration or another identified cause; the number itself is not treated.']),
      low: d('Goal: raise albumin by treating inflammation, liver disease, kidney loss, fluid overload or inadequate intake.',
        ['May raise albumin when intake is genuinely inadequate: use a protein-adequate balanced diet with clinician/dietitian guidance.', 'Does not reliably raise it when inflammation or organ disease is the cause: extra protein alone is not the solution.'],
        ['Raises albumin indirectly by treating the liver, kidney, inflammatory, absorption or fluid-balance disorder; albumin infusion has narrow indications.']),
    },
    creatinine: {
      high: d('Goal: lower creatinine only by correcting reduced filtration or a non-kidney contributor.',
        ['May lower a transient elevation: normalize hydration, avoid intense exercise and avoid creatine/cooked meat before a standardized repeat.', 'Protects kidney function: control blood pressure/glucose and avoid unnecessary NSAIDs.'],
        ['Lowers creatinine by treating the cause—restore circulation, relieve obstruction, treat infection or adjust a contributing medicine.']),
      low: d('Goal: do not directly raise creatinine; assess muscle mass, nutrition, pregnancy or liver disease.',
        ['May raise creatinine indirectly: adequate nutrition and resistance activity can increase muscle mass when appropriate.'],
        ['Treatment targets confirmed undernutrition, muscle loss or liver disease—not creatinine itself.']),
    },
    egfr: {
      high: d('Goal: do not lower eGFR; check whether an unusually high estimate reflects low creatinine or hyperfiltration.',
        ['No lifestyle action is used to lower eGFR.', 'Protects kidneys: manage glucose and blood pressure if hyperfiltration risk is present.'],
        ['Treatment targets diabetes, pregnancy-related context or low muscle mass; the estimate itself is not lowered.']),
      low: d('Goal: preserve or improve filtration and slow further decline—not force a short-term number upward.',
        ['Protects eGFR: control blood pressure/glucose, avoid tobacco, remain active and avoid recurrent dehydration/nephrotoxins.', 'Protein, sodium and potassium changes should be individualized.'],
        ['Preserves eGFR in eligible CKD: ACE inhibitor/ARB, SGLT2 inhibitor and selected additional therapies; acute reductions need cause-specific treatment.']),
    },
    uacr: {
      high: d('Goal: lower persistent urine albumin loss and kidney/cardiovascular risk.',
        ['Lowers uACR risk: good blood-pressure/glucose control, tobacco avoidance and an individualized lower-sodium pattern.', 'Improves confirmation accuracy: avoid hard exercise immediately before the repeat sample.'],
        ['Lowers albuminuria in eligible people: ACE inhibitor/ARB, SGLT2 inhibitor and selected finerenone therapy.']),
      low: d('Goal: no increase is needed; a low uACR is generally favorable.',
        ['No lifestyle action is needed to raise uACR.'],
        ['No treatment is used to raise uACR.']),
    },
    bun: {
      high: d('Goal: lower BUN by correcting dehydration, kidney dysfunction, bleeding or excessive protein/catabolic load when present.',
        ['May lower BUN: normalize hydration when safe and avoid unnecessarily high protein intake.', 'Do not overhydrate simply to lower the number.'],
        ['Lowers BUN by treating kidney injury, gastrointestinal bleeding, heart failure or another identified cause.']),
      low: d('Goal: raise BUN only by correcting inadequate protein/energy intake or another identified cause.',
        ['May raise BUN when intake is inadequate: use an appropriate protein and calorie intake.', 'Do not deliberately dehydrate to raise BUN.'],
        ['Treatment targets undernutrition, overhydration or liver disease—not BUN itself.']),
    },
    tsh: {
      high: d('Goal: lower TSH toward an individualized target by confirming and treating hypothyroidism or absorption/dosing problems.',
        ['Supports lowering when levothyroxine is prescribed: take it consistently and separate it from interfering iron, calcium or food as instructed.', 'Avoid high-dose iodine/kelp.'],
        ['Lowers TSH in confirmed hypothyroidism: clinician-adjusted levothyroxine and treatment of absorption or interaction problems.']),
      low: d('Goal: raise TSH toward range by treating hyperthyroidism or reducing excessive thyroid-hormone exposure under supervision.',
        ['No diet reliably raises TSH; avoid high-dose iodine and disclose biotin before testing.'],
        ['Raises TSH by treating hyperthyroidism or reducing excessive replacement; options can include antithyroid medicine, radioactive iodine or surgery.']),
    },
    freet4: {
      high: d('Goal: lower free T4 by treating hyperthyroidism, thyroiditis or excessive replacement.',
        ['No diet reliably lowers true free T4; avoid high-dose iodine and disclose biotin.', 'Use thyroid medication exactly as prescribed.'],
        ['Lowers free T4: clinician-adjusted thyroid replacement or cause-specific antithyroid treatment.']),
      low: d('Goal: raise free T4 by confirming and treating primary or central hypothyroidism.',
        ['No food or supplement reliably replaces thyroid hormone; take prescribed therapy consistently.'],
        ['Raises free T4 in primary hypothyroidism: clinician-adjusted levothyroxine; central patterns need endocrine evaluation.']),
    },
    hemoglobin: {
      high: d('Goal: lower haemoglobin only by correcting dehydration/low oxygen or treating true erythrocytosis.',
        ['May lower a concentrated result: normal hydration.', 'Lowers stimulus to excess red cells: stop smoking and evaluate sleep apnoea/low oxygen.'],
        ['Lowers true erythrocytosis: cause-specific treatment, sometimes phlebotomy and specialist therapy.']),
      low: d('Goal: raise haemoglobin by identifying and treating blood loss, deficiency, kidney disease, inflammation or marrow disease.',
        ['Raises haemoglobin only when deficient: iron-, B12- or folate-containing foods and replacement after confirmation.', 'Do not take iron without establishing iron deficiency and the cause.'],
        ['Raises haemoglobin: diagnosis-specific iron/B12 replacement; selected ESA or transfusion use depends on cause, severity and symptoms.']),
    },
    wbc: {
      high: d('Goal: lower WBC by treating infection, inflammation, smoking/medicine effects or a marrow disorder—not by suppressing the count.',
        ['May lower a persistent reactive count: stop smoking and recover with adequate sleep/nutrition.', 'No supplement safely lowers WBC directly.'],
        ['Lowers WBC by treating the diagnosed infection/inflammatory or marrow cause and reviewing contributing medicines.']),
      low: d('Goal: raise WBC only by treating the cause and reducing infection risk.',
        ['No “immune booster” reliably raises WBC; use clinician-specific infection precautions when neutropenic.'],
        ['Raises selected low counts: treatment of deficiency/infection or medicine adjustment; G-CSF is reserved for selected neutropenia.']),
    },
    platelets: {
      high: d('Goal: lower platelets by treating a reactive cause or a confirmed marrow disorder.',
        ['No lifestyle method directly lowers platelets; treat iron deficiency/inflammation when confirmed and avoid tobacco.', 'Do not start aspirin solely because the count is high.'],
        ['Lowers platelets in selected myeloproliferative disease: specialist cytoreductive treatment; reactive counts fall when the cause resolves.']),
      low: d('Goal: raise platelets by confirming the count and treating immune, medicine, liver/spleen or marrow causes.',
        ['No food reliably raises platelets; reduce alcohol only when it is a contributor.', 'Avoid unapproved medicines/supplements that increase bleeding risk.'],
        ['Raises platelets in selected immune thrombocytopenia: corticosteroids, IVIG or thrombopoietin-receptor therapy; treatment depends on bleeding risk.']),
    },
    hematocrit: {
      high: d('Goal: lower hematocrit by correcting dehydration/low oxygen or treating true erythrocytosis.',
        ['May lower a concentrated value: normal hydration.', 'Lowers low-oxygen stimulus: stop smoking and evaluate sleep apnoea/lung disease.'],
        ['Lowers true erythrocytosis: diagnosis-specific treatment, sometimes phlebotomy and specialist therapy.']),
      low: d('Goal: raise hematocrit by treating the cause of anaemia or dilution.',
        ['Raises it only when deficient: adequate iron, B12 and folate after confirmation.', 'Do not take iron simply to raise hematocrit.'],
        ['Raises hematocrit: cause-specific replacement, treatment of bleeding/chronic disease, or selected ESA/transfusion use.']),
    },
    mcv: {
      high: d('Goal: lower MCV by correcting B12/folate deficiency, alcohol/thyroid/liver effects or a marrow cause.',
        ['May lower MCV when relevant: reduce alcohol and correct a confirmed B12/folate intake deficiency.', 'Do not take folate alone until B12 deficiency has been considered.'],
        ['Lowers MCV indirectly: replace the confirmed deficiency or treat thyroid, liver or marrow disease.']),
      low: d('Goal: raise MCV by identifying iron deficiency versus thalassaemia, inflammation or another cause.',
        ['Raises MCV only in iron deficiency: iron-rich foods and prescribed replacement after confirmation.', 'Do not take iron for thalassaemia trait unless iron deficiency also exists.'],
        ['Raises MCV indirectly: treat confirmed iron deficiency/blood loss; inherited haemoglobin disorders need diagnosis-specific care.']),
    },
    ferritin: {
      high: d('Goal: do not increase iron; lower ferritin only after distinguishing inflammation/liver disease from true iron overload.',
        ['Prevents further increase: avoid unnecessary iron supplements.', 'May lower ferritin when liver/metabolic factors contribute: reduce alcohol and improve metabolic health; this does not treat genetic iron overload.'],
        ['Lowers ferritin in confirmed iron overload: therapeutic phlebotomy, or specialist chelation in selected cases.', 'Lowers inflammation-related ferritin by treating the underlying infection/inflammatory or liver condition.']),
      low: d('Goal: raise ferritin by replacing iron and finding the source of iron loss or poor absorption.',
        ['Raises ferritin: iron-rich foods; vitamin C can improve absorption of plant iron.', 'Does not solve the cause: heavy menstrual or gastrointestinal blood loss still needs evaluation.'],
        ['Raises ferritin: oral iron is common first-line treatment; IV iron is used for selected intolerance, malabsorption or higher-need settings.']),
    },
    vitd: {
      high: d('Goal: lower vitamin D exposure and treat hypercalcaemia risk when excess is confirmed.',
        ['Lowers further exposure: stop non-prescribed high-dose vitamin D and review all supplement sources with a clinician.', 'Do not deliberately avoid ordinary foods or safe outdoor activity solely to lower the level.'],
        ['Lowers a toxic level indirectly: stop excess supplementation and medically manage hypercalcaemia/kidney complications.']),
      low: d('Goal: raise vitamin D enough for the relevant indication without target-chasing.',
        ['Raises vitamin D: fortified foods, oily fish and an evidence-based maintenance supplement when appropriate.', 'Safe sun exposure may contribute but tanning beds are not recommended.'],
        ['Raises vitamin D: clinician-selected vitamin D2/D3 replacement; malabsorption, kidney/liver disease and calcium disorders need specialized regimens.']),
    },
    vitb12: {
      high: d('Goal: do not try to lower B12 unless excess supplementation is identified; investigate an unexplained high result in context.',
        ['May lower supplement-related B12: review non-prescribed supplement dose with a clinician; do not restrict nutritious foods.', 'No detox or special diet is recommended.'],
        ['Treatment targets an identified liver, kidney, inflammatory or blood disorder—not the B12 number itself.']),
      low: d('Goal: raise B12 and prevent neurologic or blood complications while identifying the cause.',
        ['Raises B12: reliable fortified foods or supplements for dietary deficiency; avoid recreational nitrous oxide.'],
        ['Raises B12: oral replacement for many causes; lifelong intramuscular replacement is used for selected irreversible malabsorption causes.']),
    },
    sodium: {
      high: d('Goal: lower sodium concentration gradually by correcting water deficit or the identified cause—not by rapidly forcing water.',
        ['May lower it when ordinary dehydration is confirmed: follow an individualized rehydration plan.', 'Do not self-correct a marked abnormality with large water loads.'],
        ['Lowers sodium safely: controlled fluids and cause-specific treatment with a carefully managed correction rate.']),
      low: d('Goal: raise sodium concentration gradually by treating water excess, medicine effects or volume/hormonal causes—not by taking salt indiscriminately.',
        ['May raise it only in selected causes: follow an individualized fluid plan; do not force salt or restrict water without guidance.'],
        ['Raises sodium safely: cause-specific fluid restriction, saline, medicine changes or hormonal treatment with a carefully limited correction rate.']),
    },
    potassium: {
      high: d('Goal: lower potassium after confirming the result and assessing ECG, kidney function and medicines.',
        ['Prevents further increase: avoid potassium supplements and salt substitutes until reviewed.', 'Dietary lowering should be individualized; do not broadly restrict nutritious foods without kidney/dietitian advice.'],
        ['Lowers potassium: medication adjustment, diuretics or potassium binders; severe hyperkalaemia needs urgent hospital treatment.']),
      low: d('Goal: raise potassium and magnesium safely while treating ongoing losses.',
        ['May raise potassium in mild confirmed deficiency: potassium-rich foods only when kidney function and medicines make this safe.', 'Address vomiting, diarrhoea or laxative misuse and maintain balanced intake.'],
        ['Raises potassium: oral or IV potassium plus magnesium and cause-specific treatment; severe or symptomatic deficiency needs urgent assessment.']),
    },
  };

  for (const biomarker of B.data.catalogList()) {
    if (biomarker.guidance) biomarker.guidance.directional = advice[biomarker.id];
  }
})(window.Baseline);
